ops:
  ttb_partitioned:
    config:
      max_sequence_per_batch: 99999
      consecutive_failure_threshold: 10
      s3_bucket: "ciq-dagster"
      raw_data_prefix: "1-ttb-raw-data"
      ssl_verify: false
      max_retries: 3
      request_delay_seconds: 0.5

  ttb_raw_extraction:
    config:
      s3_bucket: "ciq-dagster"
      s3_input_prefix: "1-ttb-raw-data"
      enable_parsing_validation: true
      data_quality_analysis: true

  ttb_cleaned_data:
    config:
      s3_bucket: "ciq-dagster"
      s3_output_prefix: "2-ttb-processed-data"
      enable_deduplication: true
      data_quality_analysis: true
      create_partitioned_output: true

  ttb_structured_output:
    config:
      s3_bucket: "ciq-dagster"
      s3_output_prefix: "2-ttb-processed-data"
      create_partitioned_output: true
      validate_schema: true
      data_quality_analysis: true

  ttb_consolidated_data:
    config:
      bucket_name: "ciq-dagster"
      s3_output_prefix: "3-ttb-consolidated"
      create_partitioned_output: true
      data_quality_analysis: true
      deduplication_enabled: true

resources:
  s3_resource:
    config:
      region_name: "us-east-1"