# Production environment configuration for TTB pipeline
# This file contains settings optimized for production deployment

# Environment identification
deployment_environment: "prod"

# S3 Configuration - Production
s3:
  bucket: "ttb-production-data"  # Production bucket
  prefixes:
    raw_data: "1-ttb-raw-data"
    processed_data: "2-ttb-processed-data"
    dimensional_data: "3-ttb-dimensional-data"

# Processing limits for production (larger batches for efficiency)
processing:
  max_sequence_per_batch: 10000
  request_delay_seconds: 1.0  # More conservative rate limiting
  max_retries: 5
  ssl_verify: false  # TTB has cert issues
  enable_data_quality_checks: true
  enable_deduplication: true

# Receipt methods to process in production
receipt_methods:
  - 1  # e-filed
  - 2  # mailed
  - 3  # overnight
  - 0  # hand-delivered

# Dimensional modeling settings
dimensional:
  date_start_year: 2015
  date_end_year: 2035  # Extended range for production
  enable_surrogate_keys: true

# Production-specific settings
prod_settings:
  enable_debug_logging: false
  create_partitioned_output: true
  enable_monitoring: true
  enable_alerting: true